services:
  server-v4:
    build:
      context: .
      dockerfile: ./cmd/server-v4/Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - ./cmd/server-v4/.env
    environment:
      ENVIRONMENT: development
