services:
  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      ENVIRONMENT: development
      FIRESTORE_EMULATOR_HOST: firebase:8000
    depends_on:
      - firebase

  game:
    build:
      context: .
      dockerfile: ./cmd/game/Dockerfile
      target: development
    ports:
      - 8081:8080
    volumes:
      - ./:/app
    environment:
      ENVIRONMENT: development
      FIRESTORE_EMULATOR_HOST: firebase:8000
    depends_on:
      - firebase

  firebase:
    build:
      context: .
      dockerfile: ./cmd/firebase/Dockerfile
    ports:
      - 4000:4000
      - 8000:8000
    volumes:
      - ./cmd/firebase/.firebaserc:/firebase/.firebaserc
      - ./cmd/firebase/firebase.json:/firebase/firebase.json
