services:
  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./:/internal/api
    environment:
      - ENVIRONMENT=development
    depends_on:
      firestore:
        condition: service_healthy
      redis:
        condition: service_healthy

  game:
    build:
      context: .
      dockerfile: ./cmd/game/Dockerfile
      target: development
    ports:
      - 8081:8080
    volumes:
      - ./:/internal/game
    environment:
      - ENVIRONMENT=development
    depends_on:
      firestore:
        condition: service_healthy
      redis:
        condition: service_healthy

  firestore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    ports:
      - 8200:8200
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8200
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:8200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis_data:
    driver: local
