name: Deploy Servers

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

jobs:
  deploy-server-v4:
    name: Deploy Server v4
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: Configure Docker to use the gcloud CLI
      run: gcloud auth configure-docker --quiet

    - name: Build a Docker image
      run: docker build -t ${{ env.IMAGE }} -f cmd/server-v4/Dockerfile .

    - name: Push the Docker image
      run: docker push ${{ env.IMAGE }}

    - name: Deploy to Cloud Run
      run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --port 8080 \
            --project $GCP_PROJECT_ID \
            --region $GCP_REGION \
            --platform managed \
            --allow-unauthenticated \
            --quiet
