name: E2E Test

on: [ push ]

jobs:
  e2e:
    name: E2E test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: false

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.45.5

      - name: Create dummy .env
        run: >
            deno run --allow-write=. .github/createEnviron.ts
            --JWT_SECRET_KEY secret
            --GOOGLE_CLOUD_PROJECT_ID project-id

      - name: Build and Start containers
        run: docker compose up -d

      - name: DEBUG docker-compose
        run: docker compose ps

      - name: E2E test
        run: go test -timeout 10s -count=1 -v ./e2e/...
