name: Deploy

on:
  push:
    branches:
      - main
      - v2-develop

jobs:
  backend-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.0

    - name: Create environ.yaml
      run: node .github/createEnviron.js ${{ secrets.DATABASE_URL }} ${{ secrets.JWT_SECRET }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.8.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: app.yaml
        credentials: ${{ secrets.GCP_SA_KEY }}
        version: v1
