name: Set Association

on:
  workflow_dispatch:
    inputs:
      environment:
        description: デプロイ環境
        required: true
        type: choice
        options:
        - stg
        - prd
      association_id:
        description: 協会ID
        required: true
        type: string
      name:
        description: 協会名
        required: true
        type: string
      password:
        description: パスワード
        required: true
        type: string
      contractStartedAt:
        description: 契約開始日 (YYYY-MM-DD)
        required: true
        type: string
      contractType:
        description: 契約タイプ
        required: true
        type: choice
        options:
        - 3month
        - 1year
        - 3year
        - 5year
        - free

permissions:
  id-token: write
  contents: read

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ secrets.STG_GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-actions-oidc-provider
  SERVICE_ACCOUNT: github-actions@${{ secrets.STG_GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com

jobs:
  set_association:
    name: Set Association
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud by OpenID Connect
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: false

      - name: Set Association Script
        env:
          ASSOCIATION_ID: ${{ github.event.inputs.association_id }}
          NAME: ${{ github.event.inputs.name }}
          PASSWORD: ${{ github.event.inputs.password }}
          CONTRACT_STARTED_AT: ${{ github.event.inputs.contractStartedAt }}
          CONTRACT_TYPE: ${{ github.event.inputs.contractType }}
        run: |
          echo "::add-mask::$ASSOCIATION_ID"
          echo "::add-mask::$NAME"
          echo "::add-mask::$PASSWORD"
          echo "::add-mask::$CONTRACT_STARTED_AT"
          echo "::add-mask::$CONTRACT_TYPE"

          go run main.go \
            -environment "${{ github.event.inputs.environment }}" \
            -association_id "$ASSOCIATION_ID" \
            -name "$NAME" \
            -password "$PASSWORD" \
            -contract_started_at "$CONTRACT_STARTED_AT" \
            -contract_type "$CONTRACT_TYPE"
