name: Terraform Apply

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ secrets.STG_GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-oidc/providers/github-actions-oidc-provider
  SERVICE_ACCOUNT: github-actions@${{ secrets.STG_GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, game, auth]
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud by OpenID Connect
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./cmd/${{ matrix.service }}/Dockerfile
          target: production
          tags: asia-northeast1-docker.pkg.dev/${{ secrets.STG_GOOGLE_CLOUD_PROJECT_ID }}/${{ matrix.service }}-service/service:${{ github.sha }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    env:
      TF_VAR_api_service_image: asia-northeast1-docker.pkg.dev/${{ secrets.STG_GOOGLE_CLOUD_PROJECT_ID }}/api-service/service:${{ github.sha }}
      TF_VAR_game_service_image: asia-northeast1-docker.pkg.dev/${{ secrets.STG_GOOGLE_CLOUD_PROJECT_ID }}/game-service/service:${{ github.sha }}
      TF_VAR_auth_service_image: asia-northeast1-docker.pkg.dev/${{ secrets.STG_GOOGLE_CLOUD_PROJECT_ID }}/auth-service/service:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud by OpenID Connect
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=./terraform/stg init

      - name: Terraform Plan
        run: terraform -chdir=./terraform/stg plan

      - name: Terraform Apply
        run: terraform -chdir=./terraform/stg apply -auto-approve
